apiVersion: v2
name: zalando-postgres
description: Zalando Postgres Operator + PostgreSQL + PgBouncer + S3 backups
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: pgadmin4
    version: "1.*"
    repository: https://helm.runix.net
    condition: pgadmin.enabled

  - name: postgres-operator
    version: "1.*"
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    condition: operator.enabled


